
name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Deploy to PyPi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-

    - name: Setup pirogue
      run: |
        VERSION=${GITHUB_REF:-0.0.0}
        VERSION=${VERSION##*/}
        sed -i "s/__VERSION__/${VERSION}/g" setup.py
        python setup.py sdist
        pirogue -v
    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}